version: '3.8'

services:
  app:
    build: .
    container_name: app
    ports:
      - "3000:3000"
    volumes:
      - ./backend/streams:/app/backend/streams
      - ./frontend:/app/frontend
    environment:
      - PORT=3000
    restart: always

  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./backend/streams:/app/backend/streams
      - ./frontend:/app/frontend
    depends_on:
      - app
    restart: always
